[project]
name = "nbrb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "apscheduler>=3.11.3",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "ruff>=0.16.6",
    "sqlmodel>=0.0.42",
]

[project.scripts]
nbrb = "nbrb:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
exclude = [
    "migrations",
]